media:
  input: content
  output: /
  categories: [image]
content:
  - name: wiki
    label: Wiki
    type: collection
    path: content
    filename: "{primary}.md"
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: type, label: Type, type: select, required: true, options: { values: [docs] }, default: docs }
      - name: body
        label: Body
        type: rich-text
components:
  alt-image:
    label: Image with ALT text
    type: object
    fields:
      - name: src
        label: Image
        type: image
      - name: alt
        label: ALT text
        type: string