media:
  input: content
  output: /
  categories: [image]
content:
  - name: wiki
    label: Wiki
    type: collection
    path: content
    filename: "{primary}.md"
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: type, label: Type, type: select, required: true, options: { values: [docs] }, default: docs }
      #- name: body
      #  label: Body
      #  type: rich-text
      - name: blocks
        label: Body
        type: block
        list: true
        blockKey: type # Optional: customize the key used to store the block name, defaults to `_block`
        blocks:
          # Each item defines a possible block structure the user can select.
          # These typically use 'component' or define 'fields' directly.
          - name: alt-image
            label: Add Local Image
            component: alt-image
          - name: remote-image
            label: Add Remote Image
            component: remote-image
          - name: text
            label: Add Text Block
            fields:
              - name: content
                label: Text Content
                type: rich-text
          - name: callout
            label: Add Callout
            component: callout
components:
  alt-image:
    label: Image
    type: object
    fields:
      - name: src
        label: Image
        type: image
      - name: alt
        label: ALT text
        type: string
  remote-image:
    label: Remote image
    type: object
    fields:
      - name: src
        label: Image
        type: string
      - name: alt
        label: ALT text
        type: string
  callout:
    label: Callout
    type: object
    fields:
      - name: type
        label: Type
        default: default
        type: select
        options:
          values: [default, info, warning, error]
      - name: text
        label: Text
        type: rich-text